### ISSUE TITLE
Error: The directory is not empty.: '...\azure\login\v1\node_modules\...'

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/login#160]
**Describe the bug**
I posted this issue in actions/runner repository as well since I don't know who caused the error. The error occurs during "Set up job" step, but always an error about "The directory is not empty" in a node_modules foder in "azure\login\v1". Here is the issue I created in actions/runner repository:
https://github.com/actions/runner/issues/1436

An occasional error occurs during "Set up job" step that is owned by Github Actions and not described in any user workflow file. This is the error:
```
Error: The directory is not empty. : 'C:\...\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
```
```
Error: The directory is not empty. : 'C:\...\_work\_actions\azure\login\v1\node_modules\semver'
```
This is for a workflow that runs many matrix jobs. There were around 26 jobs in total, and most of them run a step called `azure/login@v1`. The repository for this step is below:
https://github.com/Azure/login

**To Reproduce**
There is no consistent reproduction, nor do I know how to reproduce it since I don't own the "Set up job" step.

**Expected behavior**

I expect there to be no error. I am not sure why the "Set up job" step is expecting `C:\...\_work\_actions\azure\login\v1\node_modules\jest-circus\build` to be empty as I don't own "Set up job" step since it is run by default by Github Actions for all workflow jobs.

I log in a bunch of times in many jobs using azure/login, which might have contributed the the rare error. Here is the repository of the `azure/login@v1` step I use throughout the workflow file:
https://github.com/Azure/login

## Runner Version and Platform
Version of your runner?
'2.283.3'

OS of the machine running the runner? OSX/Windows/Linux/...
Windows Server 2019 Datacenter

## What's not working?
<img width="833" alt="github-actions-setup-job-error" src="https://user-images.githubusercontent.com/19400755/138969118-31bf6df9-a734-4979-9f74-852e4dbdbb95.png">

## Job Log 
Output
```
Error: The directory is not empty. : 'C:\...\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
```

## Runner and Worker's Diagnostic Logs
There is only the worker log:
```
[2021-10-26 20:33:38Z INFO JobServerQueue] Job timeline record has been updated for the first time.
[2021-10-26 20:33:47Z ERR  JobExtension] Caught exception from JobExtension Initialization: System.IO.IOException: The directory is not empty. : 'C:\<PATH TO RUNNER>\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2021-10-26 20:33:47Z ERR  JobRunner] Job initialize failed.
[2021-10-26 20:33:47Z ERR  JobRunner] Caught exception from InitializeJob: System.IO.IOException: The directory is not empty. : 'C:\<PATH TO RUNNER>\_work\_actions\azure\login\v1\node_modules\jest-circus\build'
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at GitHub.Runner.Sdk.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at GitHub.Runner.Worker.ActionManager.PrepareActionsAsync(IExecutionContext executionContext, IEnumerable`1 steps, Guid rootStepId)
   at GitHub.Runner.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
```

I edited the log by shortening the path to runner with <PATH TO RUNNER>

**Comment by BALAGA-GAYATRI** [comment]
Hey @TheOnlyWei This doesn't seem like an azure/login action issue. You might get more insights from [actions/runner#1436](https://github.com/actions/runner/issues/1436) issue. Feel feel to reopen if there is any login specific error :)
