### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by sdebruyn** [Azure/login#33]
I get the following error message when trying to use this action

```
2020-05-19T09:49:42.1243051Z Run Azure/login@master
2020-05-19T09:49:42.1243192Z with:
2020-05-19T09:49:42.1243301Z   enable-AzPSSession: true
2020-05-19T09:49:42.1243975Z   creds: {"clientId":"***","clientSecret":"***","subscriptionId":"***","tenantId":"***"}
2020-05-19T09:49:42.1244128Z env:
2020-05-19T09:49:42.1244231Z   tf_version: latest
2020-05-19T09:49:42.1244339Z   go_version: ^1.14.3
2020-05-19T09:49:42.1244474Z   ARM_CLIENT_ID: ***
2020-05-19T09:49:42.1244601Z   ARM_CLIENT_SECRET: ***
2020-05-19T09:49:42.1244732Z   ARM_SUBSCRIPTION_ID: ***
2020-05-19T09:49:42.1244862Z   ARM_TENANT_ID: ***
2020-05-19T09:49:42.1244980Z   GOROOT: /opt/hostedtoolcache/go/1.14.3/x64
2020-05-19T09:49:42.1245090Z   GOPATH: /home/runner/go
2020-05-19T09:49:42.1245212Z   TERRAFORM_CLI_PATH: /home/runner/work/_temp/ade9d526-d089-4c69-8237-ea31dc5db98a
2020-05-19T09:49:42.1245431Z 
2020-05-19T09:49:42.1555618Z internal/modules/cjs/loader.js:800
2020-05-19T09:49:42.1556100Z     throw err;
2020-05-19T09:49:42.1556376Z     ^
2020-05-19T09:49:42.1556668Z 
2020-05-19T09:49:42.1557254Z Error: Cannot find module '@actions/core'
2020-05-19T09:49:42.1557395Z Require stack:
2020-05-19T09:49:42.1557707Z - /home/runner/work/_actions/Azure/login/master/lib/main.js
2020-05-19T09:49:42.1557887Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2020-05-19T09:49:42.1558058Z     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2020-05-19T09:49:42.1558219Z     at Module.require (internal/modules/cjs/loader.js:852:19)
2020-05-19T09:49:42.1558372Z     at require (internal/modules/cjs/helpers.js:74:18)
2020-05-19T09:49:42.1558549Z     at Object.<anonymous> (/home/runner/work/_actions/Azure/login/master/lib/main.js:19:27)
2020-05-19T09:49:42.1558715Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-05-19T09:49:42.1558876Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-05-19T09:49:42.1559045Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2020-05-19T09:49:42.1559202Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-05-19T09:49:42.1559360Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
2020-05-19T09:49:42.1560216Z   code: 'MODULE_NOT_FOUND',
2020-05-19T09:49:42.1560682Z   requireStack: [ '/home/runner/work/_actions/Azure/login/master/lib/main.js' ]
2020-05-19T09:49:42.1560806Z }
2020-05-19T09:49:42.1662369Z Cleaning up orphan processes
```

This is the relevant portion of my workflow:

```yml
  tests:
    name: "tests"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: "^1.14.3"

      - name: Set GOPATH
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$GOPATH/bin"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@master
        with:
          terraform_version: "latest"

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          enable-AzPSSession: true
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
```

**Comment by sdebruyn** [comment]
Seems to happen on master, but not on v1.1

**Comment by eaarora-ms** [comment]
@sdebruyn We do not check-in node modules on the master branch. Please use the releases branch.
