### ISSUE TITLE
Login @v2 error registering cloud profile when used against AzureStack

### ISSUE THREAD

**Issue by mikhail-teslya** [Azure/login#459]
Hello 
we used `@v1` for our logins to AzureStack, and it worked fine until we were hit by [447](https://github.com/Azure/login/issues/447) and had to migrate to `@v2`. After we switched versions, the login step started failing with the below log:
```
Run azure/login@v2
  with:
    creds: ***
    environment: AzureStack
    enable-AzPSSession: true
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
  env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
##[debug]Reading creds in JSON...
::add-mask::***
::add-mask::***
Running Azure CLI Login.
##[debug]Azure CLI path: /usr/bin/az
##[debug]Azure CLI version used:
##[debug]azure-cli                         2.61.0
##[debug]
##[debug]core                              2.61.0
##[debug]telemetry                          1.1.0
##[debug]
##[debug]Extensions:
##[debug]azure-devops                       1.0.1
##[debug]
##[debug]Dependencies:
##[debug]msal                              1.28.0
##[debug]azure-mgmt-resource               23.1.1
##[debug]
##[debug]Python location '/opt/az/bin/python3'
##[debug]Extensions directory '/opt/az/azcliextensions'
##[debug]
##[debug]Python (Linux) 3.11.8 (main, May 16 2024, 03:47:28) [GCC 11.4.0]
##[debug]
##[debug]Legal docs and information: aka.ms/AzureCliLegal
##[debug]
##[debug]
##[debug]Your CLI is up-to-date.
##[debug]
Unregistering cloud: "azurestack" first if it exists
/usr/bin/az cloud set -n azurestack
/usr/bin/az cloud unregister -n azurestack
ERROR: The cloud 'azurestack' is not registered.
Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: The process '/usr/bin/az' failed with exit code 1
##[debug]    at ExecState._setResult (/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2333:25)
##[debug]    at ExecState.CheckComplete (/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2316:18)
##[debug]    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2210:27)
##[debug]    at ChildProcess.emit (node:events:519:28)
##[debug]    at maybeClose (node:internal/child_process:1105:16)
##[debug]    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
ERROR: The cloud 'azurestack' is not registered.
Ignore cloud not registered error: "Error: The process '/usr/bin/az' failed with exit code 1"
Registering cloud: "azurestack" with ARM endpoint: "https://management.<hiddenhost>.domain"
/usr/bin/az cloud register -n azurestack --endpoint-resource-manager "https://management.<hiddenhost>.domain" --suffix-keyvault-dns ".vault.<hiddenhost>.domain" --suffix-storage-endpoint "<hiddenhost>.domain" --profile "2019-03-01-hybrid"
ERROR: az cloud register: '"2019-03-01-hybrid"' is not a valid value for '--profile'. Allowed values: latest, 2017-03-09-profile, 2018-03-01-hybrid, 2019-03-01-hybrid, 2020-09-01-hybrid.
Did you mean '2019-03-01-hybrid' ?

Examples from AI knowledge base:
az cloud register -n MyCloud --cloud-config @"cloud.json" ("cloud.json" supports all the endpoint and suffix options in camel case or the JSON output format from `az cloud show`. See the example content below.) *** "endpointActiveDirectory": "https://login.microsoftonline.us", "suffixAcrLoginServerEndpoint": ".azurecr.us" *** or *** "endpoints":*** "activeDirectory": "https://login.microsoftonline.us" ***, "suffixes":*** "acrLoginServerEndpoint": ".azurecr.us" *** ***
Register a cloud with a config file

https://aka.ms/cli_ref
Read more about the command in reference docs
Error: Error while trying to register cloud "azurestack"
/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2333
                error = new Error(`The process '$***this.toolPath***' failed with exit code $***this.processExitCode***`);
                        ^

Error: The process '/usr/bin/az' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2333:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2316:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/login/v2/lib/main/index.js:2210:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v20.13.1
```
The workflow step is as follows:
```
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: "AzureStack"
        enable-AzPSSession: true
```
I am repeating myself, but the only difference with the previously working code is the `@v2` tag after azure/login
Can we please get some help? Thanks

**Comment by MoChilia** [comment]
Hi @mikhail-teslya, it seems that the argument `profile` doesn't pass correctly in the workflow. Could you please try the `fix-459` branch to see if it works for you?
```yaml
- uses: azure/login@fix-459
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: "AzureStack"
        enable-AzPSSession: true
```

**Comment by mikhail-teslya** [comment]
Hi @MoChilia, thanks for the update, we'll test ASAP and get back with an update

**Comment by mikhail-teslya** [comment]
Cloud is now registered, but we got another error:
```
Run azure/login@fix-459
  with:
    creds: ***
    environment: AzureStack
    enable-AzPSSession: true
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
  env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
##[debug]Reading creds in JSON...
::add-mask::***
::add-mask::***
Running Azure CLI Login.
##[debug]Azure CLI path: /usr/bin/az
##[debug]Azure CLI version used:
##[debug]***
##[debug]  "azure-cli": "2.61.0",
##[debug]  "azure-cli-core": "2.61.0",
##[debug]  "azure-cli-telemetry": "1.1.0",
##[debug]  "extensions": ***
##[debug]    "azure-devops": "1.0.1"
##[debug]  ***
##[debug]***
##[debug]
Unregistering cloud: "azurestack" first if it exists
/usr/bin/az cloud set -n azurestack
/usr/bin/az cloud unregister -n azurestack
ERROR: The cloud 'azurestack' is not registered.
Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: The process '/usr/bin/az' failed with exit code 1
##[debug]    at ExecState._setResult (/home/runner/work/_actions/azure/login/fix-459/lib/main/index.js:2333:25)
##[debug]    at ExecState.CheckComplete (/home/runner/work/_actions/azure/login/fix-459/lib/main/index.js:2316:18)
##[debug]    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/login/fix-459/lib/main/index.js:2210:27)
##[debug]    at ChildProcess.emit (node:events:519:28)
##[debug]    at maybeClose (node:internal/child_process:1105:16)
##[debug]    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
ERROR: The cloud 'azurestack' is not registered.
Ignore cloud not registered error: "Error: The process '/usr/bin/az' failed with exit code 1"
Registering cloud: "azurestack" with ARM endpoint: "https://management.<hiddenhost>.domain"
/usr/bin/az cloud register -n azurestack --endpoint-resource-manager https://management.<hiddenhost>.domain --suffix-keyvault-dns .vault.<hiddenhost>.domain --suffix-storage-endpoint .<hiddenhost>.domain --profile 2019-03-01-hybrid
Done registering cloud: "azurestack"
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Login to AzureStack with Az Powershell
```

**Comment by mikhail-teslya** [comment]
Hello, @MoChilia do you have any news? :) Thanks

**Comment by MoChilia** [comment]
@mikhail-teslya, it appears that the process exits after registering the cloud. The subsequent login commands did not execute. Actually, the error `ERROR: The cloud 'azurestack' is not registered` should be ignored, as https://github.com/Azure/login/blob/151fd0098c71af3d948d2ec8126743aa98926f5a/src/Cli/AzureCliLogin.ts#L75-L77
I will prepare a debug release for you tomorrow.

**Comment by mikhail-teslya** [comment]
@MoChilia an error again, the output is line-to-line the same as [the previous one](https://github.com/Azure/login/issues/459#issuecomment-2162163982)

**Comment by mikhail-teslya** [comment]
@MoChilia an update: please excuse me, the output is slightly different - the exception has disappeared, full log is below:
```
Run azure/login@fix-459
  with:
    creds: ***
    environment: AzureStack
    enable-AzPSSession: true
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
  env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
##[debug]Reading creds in JSON...
::add-mask::***
::add-mask::***
Running Azure CLI Login.
##[debug]Azure CLI path: /usr/bin/az
##[debug]Azure CLI version used:
##[debug]***
##[debug]  "azure-cli": "2.61.0",
##[debug]  "azure-cli-core": "2.61.0",
##[debug]  "azure-cli-telemetry": "1.1.0",
##[debug]  "extensions": ***
##[debug]    "azure-devops": "1.0.1"
##[debug]  ***
##[debug]***
##[debug]
Registering cloud: "azurestack" with ARM endpoint: "https://management..<hiddenhost>.domain"
/usr/bin/az cloud register -n azurestack --endpoint-resource-manager https://management..<hiddenhost>.domain --suffix-keyvault-dns .vault..<hiddenhost>.domain --suffix-storage-endpoint .<hiddenhost>.domain --profile 2019-03-01-hybrid
/usr/bin/az cloud set -n azurestack
ERROR: The cloud 'azurestack' is not registered.
Error: Login failed with Error: The process '/usr/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: The process '/usr/bin/az' failed with exit code 1
##[debug]    at ExecState._setResult (/home/runner/work/_actions/azure/login/fix-459/lib/main/index.js:2333:25)
##[debug]    at ExecState.CheckComplete (/home/runner/work/_actions/azure/login/fix-459/lib/main/index.js:2316:18)
##[debug]    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/login/fix-459/lib/main/index.js:2210:27)
##[debug]    at ChildProcess.emit (node:events:519:28)
##[debug]    at maybeClose (node:internal/child_process:1105:16)
##[debug]    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
Done registering cloud: "azurestack"
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Login to AzureStack with Az Powershell
```

**Comment by MoChilia** [comment]
@mikhail-teslya, I've updated the branch `azure/login@fix-459` now. It appears that the `az cloud set` executed before `az cloud register`. Could you please try again?
 If you encounter any issues again, feel free to contact me via Teams. You can find my email on the profile. Since I don't have access to an Azure Stack environment, I need your assistance with testing this. Thanks!

**Comment by mikhail-teslya** [comment]
@MoChilia this time it worked

**Comment by MoChilia** [comment]
@mikhail-teslya, great, thanks for testing this! I've created a pull request for this bug fix and will inform when it's officially released.

**Comment by mikhail-teslya** [comment]
@MoChilia thanks for your efforts! Looking forward to the new version :)

**Comment by naveendharnamoni** [comment]
As per latest azure cli the profile value should be latest. Can you update this to pick from the property of json of stack credentials which we give as input or default to the value of 2019 if the value doesn't exist.
